<?php
/**
 * Bankai Theme functions and definitions.
 *
 * @package BankaiTheme
 * @author  GCORP LLC
 * @version 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	die; // Exit if accessed directly.
}

// Define Theme Constants.
define( 'BANKAI_THEME_PATH', get_template_directory() . '/' );
define( 'BANKAI_THEME_URL', get_template_directory_uri() . '/' );

/**
 * Include Customizer, Font Loader, and Block Patterns.
 */
require_once BANKAI_THEME_PATH . 'inc/class-theme-customizer.php';
require_once BANKAI_THEME_PATH . 'inc/class-font-loader.php';
require_once BANKAI_THEME_PATH . 'inc/class-block-patterns.php';

if ( ! function_exists( 'bankai_theme_setup' ) ) {
	/**
	 * Sets up theme defaults and registers support for various WordPress features.
	 */
	function bankai_theme_setup() {
		// Add default posts and comments RSS feed links to head.
		add_theme_support( 'automatic-feed-links' );

		// Let WordPress manage the document title.
		add_theme_support( 'title-tag' );

		// Enable support for Post Thumbnails on posts and pages.
		add_theme_support( 'post-thumbnails' );

		// Register Navigation Menus.
		register_nav_menus(
			array(
				'primary' => esc_html__( 'منوی اصلی (Primary Menu)', 'bankai-theme' ),
			)
		);

		// Switch default core markup to output valid HTML5.
		add_theme_support(
			'html5',
			array(
				'search-form',
				'comment-form',
				'comment-list',
				'gallery',
				'caption',
				'style',
				'script',
			)
		);
	}
}
add_action( 'after_setup_theme', 'bankai_theme_setup' );

if ( ! function_exists( 'bankai_theme_enqueue_assets' ) ) {
	/**
	 * Enqueue scripts and styles generated by @wordpress/scripts.
	 */
	function bankai_theme_enqueue_assets() {
		$asset_file = BANKAI_THEME_PATH . 'build/index.asset.php';

		if ( file_exists( $asset_file ) ) {
			$asset = require $asset_file;

			wp_enqueue_script(
				'bankai-theme-script',
				BANKAI_THEME_URL . 'build/index.js',
				isset( $asset['dependencies'] ) ? $asset['dependencies'] : array(),
				isset( $asset['version'] ) ? $asset['version'] : '1.0.0',
				true
			);

			if ( file_exists( BANKAI_THEME_PATH . 'build/index.css' ) ) {
				wp_enqueue_style(
					'bankai-theme-style',
					BANKAI_THEME_URL . 'build/index.css',
					array(),
					isset( $asset['version'] ) ? $asset['version'] : '1.0.0'
				);
			}
		}
	}
}
add_action( 'wp_enqueue_scripts', 'bankai_theme_enqueue_assets' );
