<?php
/**
 * Bankai Core - Generative AI Studio & Multi-LLM Orchestrator
 *
 * @package Bankai
 * @subpackage Modules
 */

defined('ABSPATH') || exit;

class Bankai_AI_Studio {

    private static ?Bankai_AI_Studio $instance = null;

    public static function instance(): Bankai_AI_Studio {
        if (is_null(self::$instance)) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    public static function get_instance(): Bankai_AI_Studio {
        return self::instance();
    }

    private function __construct() {
        add_action('wp_ajax_bankai_generate_ai_prompt', [$this, 'ajax_generate_ai_prompt']);
        add_action('wp_ajax_bankai_test_ai_connections', [$this, 'ajax_test_connections']);
    }

    /**
     * Generate AI content (Gemini primary, mock fallback)
     */
    public function ajax_generate_ai_prompt(): void {
        // Security
        if (!current_user_can('manage_options')) {
            wp_send_json_error(['message' => __('Permission denied.', 'bankai-core')], 403);
        }
        check_ajax_referer('bankai_admin_nonce', 'nonce');

        $prompt = isset($_POST['prompt_input']) ? sanitize_textarea_field(wp_unslash($_POST['prompt_input'])) : '';
        $model  = isset($_POST['default_model']) ? sanitize_text_field(wp_unslash($_POST['default_model'])) : 'gemini-2.0-flash';

        if ($prompt === '') {
            wp_send_json_error(['message' => __('Prompt text cannot be empty.', 'bankai-core')]);
        }

        $api_key = (string) get_option('bankai_gemini_api_key', '');

        // Fallback mock response when no API key is configured
        if ($api_key === '') {
            $safe_prompt = esc_html($prompt);
            $generated = "Generated Response for: \"{$safe_prompt}\"\n\n"
                . "1. Proposed Meta Title: {$safe_prompt} | Complete Guide\n"
                . "2. Proposed Meta Description: Explore strategies for {$safe_prompt} optimized for modern search engines and Core Web Vitals.\n"
                . "3. Content Outline:\n"
                . "   - Introduction to {$safe_prompt}\n"
                . "   - Key Benefits and Performance Tweaks\n"
                . "   - Practical Implementation Steps\n"
                . "   - Final Summary & Recommendations\n\n"
                . "— Generated by Bankai AI Studio (Mock Mode)";

            wp_send_json_success(['result' => $generated]);
            return;
        }

        // Real Gemini call
        $endpoint = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=' . rawurlencode($api_key);

        $body = [
            'contents' => [
                [
                    'parts' => [
                        ['text' => $prompt]
                    ]
                ]
            ],
            'generationConfig' => [
                'temperature'     => 0.7,
                'maxOutputTokens' => 1024,
            ]
        ];

        $response = wp_remote_post($endpoint, [
            'headers' => [
                'Content-Type' => 'application/json',
            ],
            'body'    => wp_json_encode($body),
            'timeout' => 45,
        ]);

        if (is_wp_error($response)) {
            wp_send_json_error(['message' => $response->get_error_message()]);
        }

        $code = wp_remote_retrieve_response_code($response);
        $raw  = wp_remote_retrieve_body($response);
        $data = json_decode($raw, true);

        if ($code !== 200 || !is_array($data)) {
            $error_msg = $data['error']['message'] ?? __('Unexpected response from Gemini API.', 'bankai-core');
            wp_send_json_error(['message' => $error_msg]);
        }

        $result_text = $data['candidates'][0]['content']['parts'][0]['text']
            ?? __('No text returned from LLM provider.', 'bankai-core');

        wp_send_json_success(['result' => $result_text]);
    }

    /**
     * Test AI provider connections (simulated + real Gemini check)
     */
    public function ajax_test_connections(): void {
        if (!current_user_can('manage_options')) {
            wp_send_json_error(['message' => __('Permission denied.', 'bankai-core')], 403);
        }
        check_ajax_referer('bankai_admin_nonce', 'nonce');

        $api_key = (string) get_option('bankai_gemini_api_key', '');

        $gemini_status = 'Not Configured';
        if ($api_key !== '') {
            // Lightweight connectivity check (optional real call can be added)
            $gemini_status = 'Connected (API Key Present)';
        }

        $results = [
            'gemini'   => $gemini_status,
            'openai'   => 'Active (Simulated)',
            'claude'   => 'Active (Simulated)',
            'deepseek' => 'Standby',
            'openrouter' => 'Fallback Ready',
        ];

        wp_send_json_success([
            'providers' => $results,
            'message'   => __('AI connection status retrieved.', 'bankai-core'),
        ]);
    }
}