<?php
/**
 * Bankai Core - LLMS.txt Generator & AI Crawler Optimizer
 *
 * @package Bankai
 * @subpackage Modules
 */

defined('ABSPATH') || exit;

class Bankai_LLMS_Txt {

    private static ?Bankai_LLMS_Txt $instance = null;

    public static function instance(): Bankai_LLMS_Txt {
        if (is_null(self::$instance)) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    public static function get_instance(): Bankai_LLMS_Txt {
        return self::instance();
    }

    private function __construct() {
        if (function_exists('bankai_is_module_active') && !bankai_is_module_active('llms_txt')) {
            return;
        }

        add_action('init', [$this, 'add_rewrite_rules']);
        add_filter('query_vars', [$this, 'add_query_vars']);
        add_action('template_redirect', [$this, 'render_llms_txt']);
        add_action('wp_ajax_bankai_generate_llms_txt', [$this, 'ajax_generate_llms_txt']);
    }

    public function add_rewrite_rules(): void {
        add_rewrite_rule('^llms\.txt$', 'index.php?bankai_llms_txt=1', 'top');
        add_rewrite_rule('^llms-full\.txt$', 'index.php?bankai_llms_txt=full', 'top');
    }

    public function add_query_vars(array $vars): array {
        $vars[] = 'bankai_llms_txt';
        return $vars;
    }

    public function render_llms_txt(): void {
        $mode = get_query_var('bankai_llms_txt');
        if (!$mode) {
            return;
        }

        nocache_headers();
        header('Content-Type: text/plain; charset=utf-8');
        header('X-Robots-Tag: noindex');

        if ($mode === 'full') {
            echo $this->generate_llms_content(true);
        } else {
            echo $this->generate_llms_content(false);
        }
        exit;
    }

    /**
     * Generate llms.txt content
     *
     * @param bool $full Whether to include more content (llms-full.txt)
     */
    public function generate_llms_content(bool $full = false): string {
        $site_name = get_bloginfo('name');
        $site_desc = get_bloginfo('description');
        $site_url  = home_url('/');

        $output  = "# {$site_name}\n";
        $output .= "> {$site_desc}\n\n";
        $output .= "## Canonical\n";
        $output .= "- {$site_url}\n\n";

        $output .= "## Important Pages\n";
        $pages = get_pages([
            'number'      => $full ? 30 : 12,
            'post_status' => 'publish',
            'sort_column' => 'menu_order,post_title',
        ]);

        if (!empty($pages) && is_array($pages)) {
            foreach ($pages as $page) {
                $permalink = get_permalink($page->ID);
                $title     = get_the_title($page->ID);
                if ($permalink && $title) {
                    $output .= "- [{$title}]({$permalink})\n";
                }
            }
        }

        $output .= "\n## Recent Posts\n";
        $posts = get_posts([
            'numberposts' => $full ? 25 : 10,
            'post_status' => 'publish',
            'orderby'     => 'date',
            'order'       => 'DESC',
        ]);

        if (!empty($posts) && is_array($posts)) {
            foreach ($posts as $post) {
                $permalink = get_permalink($post->ID);
                $title     = get_the_title($post->ID);
                if ($permalink && $title) {
                    $output .= "- [{$title}]({$permalink})\n";
                }
            }
        }

        // Optional categories for full version
        if ($full) {
            $output .= "\n## Categories\n";
            $cats = get_categories(['hide_empty' => true, 'number' => 20]);
            if (!empty($cats)) {
                foreach ($cats as $cat) {
                    $link = get_category_link($cat->term_id);
                    $output .= "- [{$cat->name}]({$link})\n";
                }
            }
        }

        $output .= "\n---\n";
        $output .= "# Generated by Bankai Core – " . gmdate('Y-m-d H:i:s') . " UTC\n";
        $output .= "# Spec: llms.txt compatible\n";

        return $output;
    }

    public function ajax_generate_llms_txt(): void {
        if (!current_user_can('manage_options')) {
            wp_send_json_error(['message' => __('Permission denied.', 'bankai-core')], 403);
        }
        check_ajax_referer('bankai_admin_nonce', 'nonce');

        $content = $this->generate_llms_content(false);

        wp_send_json_success([
            'message' => __('llms.txt successfully generated.', 'bankai-core'),
            'content' => $content,
            'url'     => home_url('/llms.txt'),
            'full_url'=> home_url('/llms-full.txt'),
        ]);
    }
}